
CREATE DATABASE IF NOT EXISTS todo_app;
USE todo_app;

CREATE TABLE IF NOT EXISTS todos (
    `No` INT AUTO_INCREMENT PRIMARY KEY,
    `Todo item` VARCHAR(255) NOT NULL,
    `Status` VARCHAR(50) NOT NULL
);
